language: python
sudo: required
dist: trusty
python:
  - "2.7"
  - "3.5.2"
before_install:
  - export PYTHONPATH=$HOME/pyrasdr
install:
  - pip install -U pip setuptools wheel
  - pip install -U pytest pytest-xdist
  - pip install -U pyserial numpy
script:
  - py.test --pyargs tests/test_*